ALTER TABLE country ADD COLUMN region TEXT;

UPDATE country as c
SET region =
    CASE c.country
        WHEN 'Afghanistan' THEN 'Asia'
        WHEN 'Algeria' THEN 'Africa'
        WHEN 'American Samoa' THEN 'Oceania'
        WHEN 'Angola' THEN 'Africa'
        WHEN 'Anguilla' THEN 'North America'
        WHEN 'Argentina' THEN 'South America'
        WHEN 'Armenia' THEN 'Asia'
        WHEN 'Australia' THEN 'Oceania'
        WHEN 'Austria' THEN 'Europe'
        WHEN 'Azerbaijan' THEN 'Asia'
        WHEN 'Bahrain' THEN 'Asia'
        WHEN 'Bangladesh' THEN 'Asia'
        WHEN 'Belarus' THEN 'Europe'
        WHEN 'Bolivia' THEN 'South America'
        WHEN 'Brazil' THEN 'South America'
        WHEN 'Brunei' THEN 'Asia'
        WHEN 'Bulgaria' THEN 'Europe'
        WHEN 'Cambodia' THEN 'Asia'
        WHEN 'Cameroon' THEN 'Africa'
        WHEN 'Canada' THEN 'North America'
        WHEN 'Chad' THEN 'Africa'
        WHEN 'Chile' THEN 'South America'
        WHEN 'China' THEN 'Asia'
        WHEN 'Colombia' THEN 'South America'
        WHEN 'Congo, The Democratic Republic of the' THEN 'Africa'
        WHEN 'Czech Republic' THEN 'Europe'
        WHEN 'Dominican Republic' THEN 'North America'
        WHEN 'Ecuador' THEN 'South America'
        WHEN 'Egypt' THEN 'Africa'
        WHEN 'Estonia' THEN 'Europe'
        WHEN 'Ethiopia' THEN 'Africa'
        WHEN 'Faroe Islands' THEN 'Europe'
        WHEN 'Finland' THEN 'Europe'
        WHEN 'France' THEN 'Europe'
        WHEN 'French Guiana' THEN 'South America'
        WHEN 'French Polynesia' THEN 'Oceania'
        WHEN 'Gambia' THEN 'Africa'
        WHEN 'Germany' THEN 'Europe'
        WHEN 'Greece' THEN 'Europe'
        WHEN 'Greenland' THEN 'North America'
        WHEN 'Holy See (Vatican City State)' THEN 'Europe'
        WHEN 'Hong Kong' THEN 'Asia'
        WHEN 'Hungary' THEN 'Europe'
        WHEN 'India' THEN 'Asia'
        WHEN 'Indonesia' THEN 'Asia'
        WHEN 'Iran' THEN 'Asia'
        WHEN 'Iraq' THEN 'Asia'
        WHEN 'Israel' THEN 'Asia'
        WHEN 'Italy' THEN 'Europe'
        WHEN 'Japan' THEN 'Asia'
        WHEN 'Kazakstan' THEN 'Asia'
        WHEN 'Kenya' THEN 'Africa'
        WHEN 'Kuwait' THEN 'Asia'
        WHEN 'Latvia' THEN 'Europe'
        WHEN 'Liechtenstein' THEN 'Europe'
        WHEN 'Lithuania' THEN 'Europe'
        WHEN 'Madagascar' THEN 'Africa'
        WHEN 'Malaysia' THEN 'Asia'
        WHEN 'Mexico' THEN 'North America'
        WHEN 'Moldova' THEN 'Europe'
        WHEN 'Morocco' THEN 'Africa'
        WHEN 'Mozambique' THEN 'Africa'
        WHEN 'Myanmar' THEN 'Asia'
        WHEN 'Nauru' THEN 'Oceania'
        WHEN 'Nepal' THEN 'Asia'
        WHEN 'Netherlands' THEN 'Europe'
        WHEN 'New Zealand' THEN 'Oceania'
        WHEN 'Nigeria' THEN 'Africa'
        WHEN 'North Korea' THEN 'Asia'
        WHEN 'Oman' THEN 'Asia'
        WHEN 'Pakistan' THEN 'Asia'
        WHEN 'Paraguay' THEN 'South America'
        WHEN 'Peru' THEN 'South America'
        WHEN 'Philippines' THEN 'Asia'
        WHEN 'Poland' THEN 'Europe'
        WHEN 'Puerto Rico' THEN 'North America'
        WHEN 'Romania' THEN 'Europe'
        WHEN 'Runion' THEN 'Africa'
        WHEN 'Russian Federation' THEN 'Europe'
        WHEN 'Saint Vincent and the Grenadines' THEN 'North America'
        WHEN 'Saudi Arabia' THEN 'Asia'
        WHEN 'Senegal' THEN 'Africa'
        WHEN 'Slovakia' THEN 'Europe'
        WHEN 'South Africa' THEN 'Africa'
        WHEN 'South Korea' THEN 'Asia'
        WHEN 'Spain' THEN 'Europe'
        WHEN 'Sri Lanka' THEN 'Asia'
        WHEN 'Sudan' THEN 'Africa'
        WHEN 'Sweden' THEN 'Europe'
        WHEN 'Switzerland' THEN 'Europe'
        WHEN 'Taiwan' THEN 'Asia'
        WHEN 'Tanzania' THEN 'Africa'
        WHEN 'Thailand' THEN 'Asia'
        WHEN 'Tonga' THEN 'Oceania'
        WHEN 'Tunisia' THEN 'Africa'
        WHEN 'Turkey' THEN 'Asia'
        WHEN 'Turkmenistan' THEN 'Asia'
        WHEN 'Tuvalu' THEN 'Oceania'
        WHEN 'Ukraine' THEN 'Europe'
        WHEN 'United Arab Emirates' THEN 'Asia'
        WHEN 'United Kingdom' THEN 'Europe'
        WHEN 'United States' THEN 'North America'
        WHEN 'Venezuela' THEN 'South America'
        WHEN 'Vietnam' THEN 'Asia'
        WHEN 'Virgin Islands, U.S.' THEN 'North America'
        WHEN 'Yemen' THEN 'Asia'
        WHEN 'Yugoslavia' THEN 'Europe'
        WHEN 'Zambia' THEN 'Africa'
      END;
SELECT * FROM country;
